apiVersion: v1
kind: Service
metadata:
  name: registration-service-svc
spec:
  ports:
    - port: 8085
      targetPort: 8085
      protocol: TCP
      name: http
  selector:
    app: registration-service-mysql
  type: LoadBalancer
