apiVersion: apps/v1
kind: Deployment
metadata:
  name: adduser-service-deployment
  labels:
    app: adduser-service-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adduser-service-mysql
  template:
    metadata:
      labels:
        app: adduser-service-mysql
    spec:
      containers:
        - image: add-user-service:1.0
          name: adduser-service-container
          imagePullPolicy: Never
          ports:
            - containerPort: 8084
          env:
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: database-name
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: user-username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: user-password
