apiVersion: v1
kind: Service
metadata:
  name: adduser-service-svc
spec:
  ports:
    - port: 8084
      targetPort: 8084
      protocol: TCP
      name: http
  selector:
    app: adduser-service-mysql
  type: LoadBalancer
